import pytest
from extraction_ops.load_to_md import process_lines
from extraction_ops.models import CleanOutPut, ToolBelt

# --test_1--
test_1 = [
    "Lorem ipsum dolor sit amet consectetur adipiscing elit. ",
    "Urna tempor pulvinar vivamus fringilla lacus nec metus. ",
    "chunks1 nostra inceptos himenaeos orci varius natoque penatibus. ",
    "Purus est efficitur laoreet mauris pharetra vestibulum fusce. ",
    "Ligula congue sollicitudin erat viverra ac tincidunt nam. ",
    "definition1 eleifend turpis fames primis vulputate ornare sagittis. ",
    "Cubilia curae hac habitasse platea dictumst lorem ipsum. ",
    "definition5 leo eu aenean sed diam urna tempor. Taciti sociosqu ",
    "ad litora torquent per conubia nostra. Maximus eget fermentum ",
    "odio phasellus non purus est. Finibus facilisis dapibus etiam ",
    "interdum tortor ligula congue. Nullam volutpat porttitor ",
    "ullamcorper rutrum gravida cras eleifend. Senectus netus suscipit ",
    "auctor curabitur facilisi cubilia curae. Cursus mi pretium tellus ",
    "duis convallis tempus leo. Ut hendrerit semper vel class aptent ",
    "taciti sociosqu. Eros lobortis nulla molestie mattis scelerisque ",
    "maximus eget. Ante condimentum neque at luctus nibh finibus ",
    "facilisis. Arcu dignissim velit aliquam imperdiet mollis nullam ",
    "volutpat. Accumsan maecenas potenti ultricies habitant morbi ",
    "senectus netus. Vitae pellentesque sem placerat in id cursus mi. ",
    "Nisl malesuada lacinia integer nunc posuere ut hendrerit. Montes ",
    "nascetur ridiculus mus donec rhoncus eros lobortis. Suspendisse ",
    "aliquet nisi sodales consequat magna ante condimentum. Euismod ",
    "quam justo lectus commodo augue arcu dignissim. Venenatis ",
    "ultrices proin libero feugiat tristique accumsan maecenas. ",
    "Adipiscing elit quisque faucibus ex sapien vitae pellentesque. ",
    "Nec metus bibendum egestas iaculis massa nisl malesuada. Natoque ",
    "chunks5 et magnis dis parturient montes nascetur. Vestibulum ",
    "fusce dictum risus blandit quis suspendisse aliquet. Tincidunt ",
    "nam porta elementum a enim euismod quam.",
]

expected_1 = CleanOutPut(
    chunk_lines=[
        "chunks1 nostra inceptos himenaeos orci varius natoque penatibus. ",
        "Purus est efficitur laoreet mauris pharetra vestibulum fusce. ",
        "Ligula congue sollicitudin erat viverra ac tincidunt nam. ",
        "ad litora torquent per conubia nostra. Maximus eget fermentum ",
        "odio phasellus non purus est. Finibus facilisis dapibus etiam ",
        "interdum tortor ligula congue. Nullam volutpat porttitor ",
        "ullamcorper rutrum gravida cras eleifend. Senectus netus suscipit ",
        "auctor curabitur facilisi cubilia curae. Cursus mi pretium tellus ",
        "duis convallis tempus leo. Ut hendrerit semper vel class aptent ",
        "taciti sociosqu. Eros lobortis nulla molestie mattis scelerisque ",
        "maximus eget. Ante condimentum neque at luctus nibh finibus ",
        "facilisis. Arcu dignissim velit aliquam imperdiet mollis nullam ",
        "volutpat. Accumsan maecenas potenti ultricies habitant morbi ",
        "senectus netus. Vitae pellentesque sem placerat in id cursus mi. ",
        "Nisl malesuada lacinia integer nunc posuere ut hendrerit. Montes ",
        "nascetur ridiculus mus donec rhoncus eros lobortis. Suspendisse ",
        "aliquet nisi sodales consequat magna ante condimentum. Euismod ",
        "quam justo lectus commodo augue arcu dignissim. Venenatis ",
        "ultrices proin libero feugiat tristique accumsan maecenas. ",
        "Adipiscing elit quisque faucibus ex sapien vitae pellentesque. ",
        "Nec metus bibendum egestas iaculis massa nisl malesuada. Natoque ",
        "chunks5 et magnis dis parturient montes nascetur. Vestibulum ",
    ],
    definition_lines=[
        "definition1 eleifend turpis fames primis vulputate ornare sagittis. ",
        "Cubilia curae hac habitasse platea dictumst lorem ipsum. ",
        "definition5 leo eu aenean sed diam urna tempor. Taciti sociosqu ",
    ],
)

test_2 = [
    "Lorem ipsum dolor sit amet consectetur adipiscing elit. ",
    "chunks0 tempor pulvinar vivamus fringilla lacus nec metus. ",
    "Conubia nostra inceptos himenaeos orci varius natoque penatibus. ",
    "",
    "definition0 est efficitur laoreet mauris pharetra vestibulum fusce. ",
    "Ligula congue sollicitudin erat viverra ac tincidunt nam. ",
    "Cras eleifend turpis fames primis vulputate ornare sagittis. ",
    "definition6 curae hac habitasse platea dictumst lorem ipsum. ",
    "",
    "Tempus leo eu aenean sed diam urna tempor. Taciti sociosqu ",
    "ad litora torquent per conubia nostra. Maximus eget fermentum ",
    "odio phasellus non purus est. Finibus facilisis dapibus etiam ",
    "interdum tortor ligula congue. Nullam volutpat porttitor ",
    "ullamcorper rutrum gravida cras eleifend. Senectus netus suscipit ",
    "auctor curabitur facilisi cubilia curae. Cursus mi pretium tellus ",
    "duis convallis tempus leo. Ut hendrerit semper vel class aptent ",
    "taciti sociosqu. Eros lobortis nulla molestie mattis scelerisque ",
    "maximus eget. Ante condimentum neque at luctus nibh finibus ",
    "facilisis. Arcu dignissim velit aliquam imperdiet mollis nullam ",
    "volutpat. Accumsan maecenas potenti ultricies habitant morbi ",
    "senectus netus. Vitae pellentesque sem placerat in id cursus mi. ",
    "Nisl malesuada lacinia integer nunc posuere ut hendrerit. Montes ",
    "nascetur ridiculus mus donec rhoncus eros lobortis. Suspendisse ",
    "aliquet nisi sodales consequat magna ante condimentum. Euismod ",
    "quam justo lectus commodo augue arcu dignissim. Venenatis ",
    "ultrices proin libero feugiat tristique accumsan maecenas. ",
    "chunks6 elit quisque faucibus ex sapien vitae pellentesque. ",
    "Nec metus bibendum egestas iaculis massa nisl malesuada. Natoque ",
    "penatibus et magnis dis parturient montes nascetur. Vestibulum ",
    "fusce dictum risus blandit quis suspendisse aliquet. Tincidunt ",
    "nam porta elementum a enim euismod quam.",
]

expected_2 = CleanOutPut(
    chunk_lines=[
        "chunks0 tempor pulvinar vivamus fringilla lacus nec metus. ",
        "Conubia nostra inceptos himenaeos orci varius natoque penatibus. ",
        "",
        "Tempus leo eu aenean sed diam urna tempor. Taciti sociosqu ",
        "ad litora torquent per conubia nostra. Maximus eget fermentum ",
        "odio phasellus non purus est. Finibus facilisis dapibus etiam ",
        "interdum tortor ligula congue. Nullam volutpat porttitor ",
        "ullamcorper rutrum gravida cras eleifend. Senectus netus suscipit ",
        "auctor curabitur facilisi cubilia curae. Cursus mi pretium tellus ",
        "duis convallis tempus leo. Ut hendrerit semper vel class aptent ",
        "taciti sociosqu. Eros lobortis nulla molestie mattis scelerisque ",
        "maximus eget. Ante condimentum neque at luctus nibh finibus ",
        "facilisis. Arcu dignissim velit aliquam imperdiet mollis nullam ",
        "volutpat. Accumsan maecenas potenti ultricies habitant morbi ",
        "senectus netus. Vitae pellentesque sem placerat in id cursus mi. ",
        "Nisl malesuada lacinia integer nunc posuere ut hendrerit. Montes ",
        "nascetur ridiculus mus donec rhoncus eros lobortis. Suspendisse ",
        "aliquet nisi sodales consequat magna ante condimentum. Euismod ",
        "quam justo lectus commodo augue arcu dignissim. Venenatis ",
        "ultrices proin libero feugiat tristique accumsan maecenas. ",
        "chunks6 elit quisque faucibus ex sapien vitae pellentesque. ",
    ],
    definition_lines=[
        "definition0 est efficitur laoreet mauris pharetra vestibulum fusce. ",
        "Ligula congue sollicitudin erat viverra ac tincidunt nam. ",
        "Cras eleifend turpis fames primis vulputate ornare sagittis. ",
        "definition6 curae hac habitasse platea dictumst lorem ipsum. ",
    ],
)

test_3 = [
    "Urna tempor pulvinar vivamus fringilla lacus nec metus. Risus ",
    "blandit quis suspendisse aliquet nisi sodales consequat. ",
    "",
    "chunks2 maecenas potenti ultricies habitant morbi senectus ",
    "netus. Vel class aptent taciti sociosqu ad litora torquent. ",
    "Ligula congue sollicitudin erat viverra ac tincidunt nam. ",
    "Sit amet consectetur adipiscing elit quisque faucibus ex. Montes ",
    "definition2 ridiculus mus donec rhoncus eros lobortis. Aliquam ",
    "imperdiet mollis nullam volutpat porttitor ullamcorper rutrum. ",
    "Tempus leo eu aenean sed diam urna tempor. Laoreet mauris ",
    "definition7 vestibulum fusce dictum risus blandit. Venenatis ",
    "ultrices proin libero feugiat tristique accumsan maecenas. Integer ",
    "nunc posuere ut hendrerit semper vel class. Finibus facilisis ",
    "dapibus etiam interdum tortor ligula congue. Habitasse platea ",
    "dictumst lorem ipsum dolor sit amet. Natoque penatibus et magnis ",
    "chunks7  parturient montes nascetur. Lectus commodo augue arcu dignissim ",
    "velit aliquam imperdiet. Cursus mi pretium tellus duis convallis ",
    "leo. Odio phasellus non purus est efficitur laoreet mauris. ",
]

expected_3 = CleanOutPut(
    chunk_lines=[
        "chunks2 maecenas potenti ultricies habitant morbi senectus ",
        "netus. Vel class aptent taciti sociosqu ad litora torquent. ",
        "Ligula congue sollicitudin erat viverra ac tincidunt nam. ",
        "Sit amet consectetur adipiscing elit quisque faucibus ex. Montes ",
        "ultrices proin libero feugiat tristique accumsan maecenas. Integer ",
        "nunc posuere ut hendrerit semper vel class. Finibus facilisis ",
        "dapibus etiam interdum tortor ligula congue. Habitasse platea ",
        "dictumst lorem ipsum dolor sit amet. Natoque penatibus et magnis ",
        "chunks7  parturient montes nascetur. Lectus commodo augue arcu dignissim ",
    ],
    definition_lines=[
        "definition2 ridiculus mus donec rhoncus eros lobortis. Aliquam ",
        "imperdiet mollis nullam volutpat porttitor ullamcorper rutrum. ",
        "Tempus leo eu aenean sed diam urna tempor. Laoreet mauris ",
        "definition7 vestibulum fusce dictum risus blandit. Venenatis ",
    ],
)

test_4 = [
    "Ligula congue sollicitudin erat viverra ac tincidunt nam. Sit amet ",
    "consectetur adipiscing elit quisque faucibus ex. Montes chunks3 ",
    "ridiculus mus donec rhoncus eros lobortis. Aliquam imperdiet mollis ",
    "nullam volutpat porttitor ullamcorper rutrum. Tempus leo eu aenean ",
    "sed diam urna tempor. Laoreet mauris pharetra vestibulum fusce definition3 ",
    "risus blandit. Venenatis ultrices proin libero feugiat tristique ",
    "accumsan maecenas. Integer nunc posuere ut hendrerit semper vel class. ",
    "Finibus facilisis dapibus etiam interdum tortor ligula congue. Habitasse ",
    "platea dictumst lorem ipsum dolor sit amet. Natoque penatibus et magnis ",
    "dis parturient montes nascetur. Lectus commodo augue arcu dignissim velit ",
    "aliquam imperdiet. Cursus mi pretium tellus duis convallis definition8 leo. ",
    "",
    "Odio phasellus non purus est efficitur laoreet mauris. Ornare sagittis ",
    "vehicula praesent dui felis venenatis ultrices. Egestas iaculis massa ",
    "nisl malesuada lacinia integer nunc. Ante condimentum neque at luctus ",
    "nibh finibus facilisis. Auctor curabitur facilisi cubilia curae hac ",
    "habitasse platea. Conubia nostra inceptos himenaeos orci varius natoque ",
    "penatibus. Elementum a enim euismod quam justo lectus commodo. ",
    "",
    "Vitae pellentesque sem placerat in id cursus mi. Molestie mattis ",
    "scelerisque maximus eget fermentum odio phasellus. Cras eleifend turpis ",
    "fames primis vulputate ornare sagittis. Vivamus fringilla lacus nec ",
    "metus bibendum egestas iaculis. Suspendisse aliquet nisi sodales ",
    "consequat magna ante condimentum. Ultricies habitant morbi senectus ",
    "netus suscipit auctor curabitur. Taciti sociosqu ad litora torquent per ",
    "conubia nostra. Erat viverra ac tincidunt nam porta elementum a. ",
    "",
    "Adipiscing elit quisque faucibus ex sapien vitae pellentesque. Mus ",
    "donec rhoncus eros lobortis nulla molestie mattis. Nullam chunks8 ",
    "porttitor ullamcorper rutrum gravida cras eleifend. Aenean sed diam ",
    "urna tempor pulvinar vivamus fringilla. Vestibulum fusce dictum risus ",
    "blandit quis suspendisse aliquet. Libero feugiat tristique accumsan ",
    "maecenas potenti ultricies habitant. Ut hendrerit semper vel class ",
    "aptent taciti sociosqu. ",
    "",
    "Etiam interdum tortor ligula congue sollicitudin erat viverra. ",
]

expected_4 = CleanOutPut(
    chunk_lines=[
        "consectetur adipiscing elit quisque faucibus ex. Montes chunks3 ",
        "ridiculus mus donec rhoncus eros lobortis. Aliquam imperdiet mollis ",
        "nullam volutpat porttitor ullamcorper rutrum. Tempus leo eu aenean ",
        "",
        "Odio phasellus non purus est efficitur laoreet mauris. Ornare sagittis ",
        "vehicula praesent dui felis venenatis ultrices. Egestas iaculis massa ",
        "nisl malesuada lacinia integer nunc. Ante condimentum neque at luctus ",
        "nibh finibus facilisis. Auctor curabitur facilisi cubilia curae hac ",
        "habitasse platea. Conubia nostra inceptos himenaeos orci varius natoque ",
        "penatibus. Elementum a enim euismod quam justo lectus commodo. ",
        "",
        "Vitae pellentesque sem placerat in id cursus mi. Molestie mattis ",
        "scelerisque maximus eget fermentum odio phasellus. Cras eleifend turpis ",
        "fames primis vulputate ornare sagittis. Vivamus fringilla lacus nec ",
        "metus bibendum egestas iaculis. Suspendisse aliquet nisi sodales ",
        "consequat magna ante condimentum. Ultricies habitant morbi senectus ",
        "netus suscipit auctor curabitur. Taciti sociosqu ad litora torquent per ",
        "conubia nostra. Erat viverra ac tincidunt nam porta elementum a. ",
        "",
        "Adipiscing elit quisque faucibus ex sapien vitae pellentesque. Mus ",
        "donec rhoncus eros lobortis nulla molestie mattis. Nullam chunks8 ",
    ],
    definition_lines=[
        "sed diam urna tempor. Laoreet mauris pharetra vestibulum fusce definition3 ",
        "risus blandit. Venenatis ultrices proin libero feugiat tristique ",
        "accumsan maecenas. Integer nunc posuere ut hendrerit semper vel class. ",
        "Finibus facilisis dapibus etiam interdum tortor ligula congue. Habitasse ",
        "platea dictumst lorem ipsum dolor sit amet. Natoque penatibus et magnis ",
        "dis parturient montes nascetur. Lectus commodo augue arcu dignissim velit ",
        "aliquam imperdiet. Cursus mi pretium tellus duis convallis definition8 leo. ",
    ],
)

test_5 = [
    "Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex ",
    "sapien vitae pellentesque sem placerat. ",
    "",
    "In id cursus mi pretium tellus duis chunks0. Tempus leo eu aenean sed diam ",
    "urna tempor. Pulvinar vivamus fringilla lacus nec metus bibendum egestas. ",
    "Iaculis massa nisl definition0 lacinia integer nunc posuere. Ut hendrerit semper ",
    "vel class aptent taciti sociosqu. Ad litora torquent per conubia nostra inceptos ",
    "himenaeos. Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque ",
    "faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus ",
    "duis convallis. Tempus leo eu aenean sed diam urna tempor. Pulvinar vivamus ",
    "fringilla lacus nec metus definition9 egestas. Iaculis massa nisl malesuada lacinia ",
    "integer nunc posuere. Ut hendrerit semper vel class aptent taciti sociosqu. ",
    "",
    "Ad litora torquent per conubia nostra inceptos himenaeos. Lorem ipsum dolor sit ",
    "amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque ",
    "sem placerat. In id cursus mi pretium tellus duis convallis. Tempus leo eu aenean ",
    "sed diam urna tempor. Pulvinar vivamus fringilla lacus nec metus bibendum egestas. ",
    "",
    "Iaculis massa nisl malesuada lacinia integer nunc posuere. Ut hendrerit semper vel ",
    "class aptent taciti sociosqu. Ad litora torquent per conubia nostra inceptos ",
    "himenaeos. Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ",
    "ex sapien vitae pellentesque sem placerat. ",
    "",
    "In id cursus mi pretium tellus duis convallis. Tempus leo eu aenean sed diam urna ",
    "tempor. Pulvinar vivamus fringilla lacus nec metus bibendum egestas. Iaculis massa ",
    "nisl malesuada lacinia integer nunc posuere. Ut hendrerit semper vel class aptent ",
    "taciti sociosqu. Ad litora torquent per conubia nostra inceptos himenaeos. ",
    "",
    "Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien ",
    "vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis. ",
    "Tempus leo eu aenean sed diam urna tempor. Pulvinar vivamus fringilla lacus nec ",
    "metus chunks9 egestas. ",
    "",
    "Iaculis massa nisl malesuada lacinia integer nunc posuere. Ut hendrerit semper vel ",
    "class aptent taciti sociosqu. Ad litora torquent per conubia nostra inceptos himenaeos.",
]

expected_5 = CleanOutPut(
    chunk_lines=[
        "In id cursus mi pretium tellus duis chunks0. Tempus leo eu aenean sed diam ",
        "urna tempor. Pulvinar vivamus fringilla lacus nec metus bibendum egestas. ",
        "integer nunc posuere. Ut hendrerit semper vel class aptent taciti sociosqu. ",
        "",
        "Ad litora torquent per conubia nostra inceptos himenaeos. Lorem ipsum dolor sit ",
        "amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque ",
        "sem placerat. In id cursus mi pretium tellus duis convallis. Tempus leo eu aenean ",
        "sed diam urna tempor. Pulvinar vivamus fringilla lacus nec metus bibendum egestas. ",
        "",
        "Iaculis massa nisl malesuada lacinia integer nunc posuere. Ut hendrerit semper vel ",
        "class aptent taciti sociosqu. Ad litora torquent per conubia nostra inceptos ",
        "himenaeos. Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ",
        "ex sapien vitae pellentesque sem placerat. ",
        "",
        "In id cursus mi pretium tellus duis convallis. Tempus leo eu aenean sed diam urna ",
        "tempor. Pulvinar vivamus fringilla lacus nec metus bibendum egestas. Iaculis massa ",
        "nisl malesuada lacinia integer nunc posuere. Ut hendrerit semper vel class aptent ",
        "taciti sociosqu. Ad litora torquent per conubia nostra inceptos himenaeos. ",
        "",
        "Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien ",
        "vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis. ",
        "Tempus leo eu aenean sed diam urna tempor. Pulvinar vivamus fringilla lacus nec ",
        "metus chunks9 egestas. ",
    ],
    definition_lines=[
        "Iaculis massa nisl definition0 lacinia integer nunc posuere. Ut hendrerit semper ",
        "vel class aptent taciti sociosqu. Ad litora torquent per conubia nostra inceptos ",
        "himenaeos. Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque ",
        "faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus ",
        "duis convallis. Tempus leo eu aenean sed diam urna tempor. Pulvinar vivamus ",
        "fringilla lacus nec metus definition9 egestas. Iaculis massa nisl malesuada lacinia ",
    ],
)

PROCESS_LINES_TEST_DATA = [
    (test_1, expected_1),
    (test_2, expected_2),
    (test_3, expected_3),
    (test_4, expected_4),
    (test_5, expected_5),
]


@pytest.mark.parametrize("unprocessed, expected", PROCESS_LINES_TEST_DATA)
def test_process_lines(
    unprocessed: list[str], test_toolbelt: ToolBelt, expected: CleanOutPut
):
    result = process_lines(unprocessed, test_toolbelt)
    assert result == expected
